/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package calorias;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
public class Calorias1 extends javax.swing.JFrame {

    /**
     * Creates new form Calorias1
     */
    public Calorias1() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Button_Calcular = new javax.swing.JButton();
        Button_Restaurar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Text_Altura = new javax.swing.JTextField();
        Text_Edad = new javax.swing.JTextField();
        Text_Peso = new javax.swing.JTextField();
        ComboBox_Actividad = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Label_Calorias = new javax.swing.JLabel();
        RadioButton_M = new javax.swing.JRadioButton();
        RadioButton_F = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Button_Calcular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Button_Calcular.setText("Calcular");
        Button_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CalcularActionPerformed(evt);
            }
        });

        Button_Restaurar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Button_Restaurar.setText("Restaurar");
        Button_Restaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RestaurarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Altura");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Edad");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Peso");

        Text_Altura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        Text_Edad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        Text_Peso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        ComboBox_Actividad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ComboBox_Actividad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Actividades", "Sedentaria", "Ligera", "Moderada", "Dinámica", "Muy dinamica" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Cantidad diarias");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Calorías:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Calorías");

        Label_Calorias.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label_Calorias.setText("0");

        buttonGroup1.add(RadioButton_M);
        RadioButton_M.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioButton_M.setText("M");

        buttonGroup1.add(RadioButton_F);
        RadioButton_F.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioButton_F.setText("F");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(Label_Calorias))
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(Button_Calcular))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Text_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Text_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Text_Altura, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Button_Restaurar)
                                    .addGap(3, 3, 3))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(RadioButton_F)
                                    .addGap(18, 18, 18)
                                    .addComponent(RadioButton_M)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(ComboBox_Actividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Text_Altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioButton_M)
                    .addComponent(RadioButton_F))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(ComboBox_Actividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Label_Calorias))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Calcular)
                    .addComponent(Button_Restaurar))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   public void Calorias(){
        //Declaramos las variables 
        double altura,caloria, edad,peso, RBM;
        String actividad;
          //Condiciones que evalúan si los campos de Texto esta vacíos
        if (Text_Altura.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Ingrese la altura","Atención",JOptionPane.INFORMATION_MESSAGE);
            Text_Altura.requestFocus();
        }else{
            if (Text_Edad.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Ingrese la edad","Atención",JOptionPane.INFORMATION_MESSAGE);
            Text_Edad.requestFocus();
        }else{
            if (Text_Peso.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Ingrese el peso","Atención",JOptionPane.INFORMATION_MESSAGE);
            Text_Peso.requestFocus();
        }else{
            /*Métodos que convierte en un tipo double el valor que se ingrese por 
             los TextField */
            altura = Double.parseDouble(Text_Altura.getText());
            edad = Double.parseDouble(Text_Edad.getText());
            peso = Double.parseDouble(Text_Peso.getText());
            //Método para extraer el Item seleccionado en ComboBox
            actividad = ComboBox_Actividad.getSelectedItem().toString();
            //La sentencia switch
            switch(actividad){
                case"Actividades":
                     JOptionPane.showMessageDialog(null,"Seleccione unas de las actividades","Atención",JOptionPane.INFORMATION_MESSAGE);
                    break;
                    case"Sedentaria":
                        //Condición que evalúa el RadioButton si es seleccionado
                        if (RadioButton_F.isSelected()) {
                            //Formula del RITMO METABÓLICO BASAL femenino
                            RBM = 655+(9.6*peso)+(1.8*altura)-(4.7*edad);
                            caloria = (RBM*1.2);
                            Label_Calorias.setText(caloria+"");
                        }else{
                            //Formula del RITMO METABÓLICO BASAL masculino
                            RBM = 66+(13.7*peso)+(5*altura)-(6.8*edad);
                            caloria = (RBM*1.2);
                            Label_Calorias.setText(caloria+"");
                        }
                        break;
                        case"Ligera":
                        //Condición que evalúa el RadioButton si es seleccionado
                        if (RadioButton_F.isSelected()) {
                            //Formula del RITMO METABÓLICO BASAL femenino
                            RBM = 655+(9.6*peso)+(1.8*altura)-(4.7*edad);
                            caloria = (RBM*1.375);
                            Label_Calorias.setText(caloria+"");
                        }else{
                            //Formula del RITMO METABÓLICO BASAL masculino
                            RBM = 66+(13.7*peso)+(5*altura)-(6.8*edad);
                            caloria = (RBM*1.375);
                            Label_Calorias.setText(caloria+"");
                        }
                        break;
                     case"Moderada":
                        //Condición que evalúa el RadioButton si es seleccionado
                        if (RadioButton_F.isSelected()) {
                            //Formula del RITMO METABÓLICO BASAL femenino
                            RBM = 655+(9.6*peso)+(1.8*altura)-(4.7*edad);
                            caloria = (RBM*1.55);
                            Label_Calorias.setText(caloria+"");
                        }else{
                            //Formula del RITMO METABÓLICO BASAL masculino
                            RBM = 66+(13.7*peso)+(5*altura)-(6.8*edad);
                            caloria = (RBM*1.55);
                            Label_Calorias.setText(caloria+"");
                        }
                        break;
                     case"Dinamica":
                        //Condición que evalúa el RadioButton si es seleccionado
                        if (RadioButton_F.isSelected()) {
                            //Formula del RITMO METABÓLICO BASAL femenino
                            RBM = 655+(9.6*peso)+(1.8*altura)-(4.7*edad);
                            caloria = (RBM*1.725);
                            Label_Calorias.setText(caloria+"");
                        }else{
                            //Formula del RITMO METABÓLICO BASAL masculino
                            RBM = 66+(13.7*peso)+(5*altura)-(6.8*edad);
                            caloria = (RBM*1.725);
                            Label_Calorias.setText(caloria+"");
                        }
                        break;
                     case"Muy dinamica":
                        //Condición que evalúa el RadioButton si es seleccionado
                        if (RadioButton_F.isSelected()) {
                            //Formula del RITMO METABÓLICO BASAL femenino
                            RBM = 655+(9.6*peso)+(1.8*altura)-(4.7*edad);
                            caloria = (RBM*1.9);
                            Label_Calorias.setText(caloria+"");
                        }else{
                            //Formula del RITMO METABÓLICO BASAL masculino
                            RBM = 66+(13.7*peso)+(5*altura)-(6.8*edad);
                            caloria = (RBM*1.9);
                            Label_Calorias.setText(caloria+"");
                        }
                        break;
                     }
                 }
              }
         }
    }
    private void Button_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CalcularActionPerformed
        Calorias();
    }//GEN-LAST:event_Button_CalcularActionPerformed

    private void Button_RestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RestaurarActionPerformed
        Text_Altura.setText("");
        Text_Edad.setText("");
        Text_Peso.setText("");
        Label_Calorias.setText("0");
        Text_Altura.requestFocus();
        ComboBox_Actividad.setSelectedItem("Actividades");

    }//GEN-LAST:event_Button_RestaurarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calorias1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calorias1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calorias1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calorias1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calorias1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Calcular;
    private javax.swing.JButton Button_Restaurar;
    private javax.swing.JComboBox ComboBox_Actividad;
    private javax.swing.JLabel Label_Calorias;
    private javax.swing.JRadioButton RadioButton_F;
    private javax.swing.JRadioButton RadioButton_M;
    private javax.swing.JTextField Text_Altura;
    private javax.swing.JTextField Text_Edad;
    private javax.swing.JTextField Text_Peso;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
